version: '3.5'

services:

  test_nginx:
    build: .docker/nginx
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - ./src:/var/www/html
      - .docker/nginx/sites-enabled/:/etc/nginx/conf.d
      - .docker/nginx/nginx_magento.conf/:/etc/nginx/nginx_magento.conf
      - .docker/nginx/log:/var/log/nginx
    depends_on:
      - testl_php
    networks:
      application_network:
        ipv4_address: ${NGINX_CONTAINER_IPV4_ADDRESS}

  testl_php:
    build: .docker/php-fpm
    container_name: ${PHP_CONTAINER_NAME}
    depends_on:
      - test_mysql
    volumes:
      - ./src:/var/www/html
    networks:
      application_network:
        ipv4_address: ${PHP_CONTAINER_IPV4_ADDRESS}

  test_mysql:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    networks:
      application_network:
        ipv4_address: ${MYSQL_CONTAINER_IPV4_ADDRESS}

  test_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_CONTAINER_NAME}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_USER_PASSWORD}
    links:
      - test_mysql
    networks:
      application_network:
        ipv4_address: ${PHPMYADMIN_CONTAINER_IPV4_ADDRESS}

  test_varnish:
    build: .docker/varnish
    container_name: ${VARNISH_CONTAINER_NAME}
    volumes:
      - .docker/varnish:/etc/varnish
    networks:
      application_network:
        ipv4_address: ${VARNISH_CONTAINER_IPV4_ADDRESS}

  test_elasticsearch:
    image: elasticsearch:6.8.2
    container_name: ${ELASTICSEARCH_CONTAINER_NAME}
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
    networks:
      - application_network

  test_kibana:
    image: docker.elastic.co/kibana/kibana:6.8.2
    container_name: ${KIBANA_CONTAINER_NAME}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_CONTAINER_NAME}
    networks:
      - application_network

networks:
  application_network:
    driver: bridge
    name: ${NETWORK_NAME}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
